name: CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and Run Tests
      run: |
        ./gradlew build test # Pour un projet Java avec Gradle
        mvn clean verify # Pour un projet Java avec Maven

    - name: Run SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.TP1_token }}
        SONAR_HOST_URL: https://sonarcloud.io
      run: |
        ./gradlew sonarqube -Dsonar.projectKey=mon-projet -Dsonar.organization=mon-organisation -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
